spring.application.name=Cine_V2
spring.datasource.url=jdbc:postgresql://localhost:5432/cine_db
spring.datasource.username=cine_user
spring.datasource.password=cine_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Una frase larga y secreta para firmar los tokens
jwt.secret=EstaEsUnaClaveSuperSecretaYMuyLargaParaMiProyectoDeCine2026
# Tiempo de vida del Access Token (1 hora = 3600000 milisegundos)
jwt.expiration=3600000
# Tiempo de vida del Refresh Token (7 dias = 604800000 milisegundos)
jwt.refresh.expiration=604800000
